### PR TITLE
Bhs/donutsalon - More donuts...

### PR DESCRIPTION
**Pull request by azimman**
need more choices... @jmacd agrees.

### CODE REVIEW

**Comment by bg451** [comment]
🚢

**Comment by jmacd** [comment]
:rocket:

**Comment by bhs** [comment]
@azimman thank you for contributing to the 🍩aaS. Unfortunately the images all need to be exactly the same pixel dimensions as the existing donuts. :)

**Comment by azimman** [comment]
@bensigelman ....fixing....

**Comment by azimman** [comment]
All donut dimensions now match. You should be good to bake. 

🍰 + 🍞 < :donut:

**Pull request closed without merging**
